language: node_js
node_js:
  - "node"
install:
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-core.git iotaeco/iota-pico-core
  - cd iotaeco/iota-pico-core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-api.git iotaeco/iota-pico-api
  - cd iotaeco/iota-pico-api
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-pal-node.git iotaeco/iota-pal-node
  - cd iotaeco/iota-pico-pal-node
  - npm link
  - cd ../iota-pico-pal-nodejs
  - npm link @iota-pico/core @iota-pico/api @iota-pico/pal-node
  - npm install
script:
  - npm run dist
cache:
  directories:
    - "node_modules"
